### PR TITLE
Fix for issue #17 and #16

### PR DESCRIPTION
**Pull request by sgumpana**
Signed-off-by: Cloud-Native Toolkit <cloudnativetoolkit@gmail.com>

### CODE REVIEW

**Review by triceam — APPROVED** [review]
To be clear, if we remove [cpd_catalogsources.yaml](https://github.com/cloud-native-toolkit/terraform-gitops-cp4d-operator/pull/18/files#diff-fd26c478964c2214c59ad07c51785e018d30da1c28ff8d22eb16e4d1017ac810), then the necessary catalog source will be added automatically by `ibm-operator-catalog`?

**Comment by triceam** [comment]
Can you update the GitHub actions workflows to use the new shared actions.  See the files in https://github.com/cloud-native-toolkit/template-terraform-gitops/tree/main/.github/workflows as a reference.

**Comment by sgumpana** [comment]
> To be clear, if we remove [cpd_catalogsources.yaml](https://github.com/cloud-native-toolkit/terraform-gitops-cp4d-operator/pull/18/files#diff-fd26c478964c2214c59ad07c51785e018d30da1c28ff8d22eb16e4d1017ac810), then the necessary catalog source will be added automatically by `ibm-operator-catalog`?

Yes, as per CPD documentation ibm-operator-catalog alone will take care of all necessary catalog sources (expect ibm-db2uoperator-catalog, this is added in cp-catalogs)
 (https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=ccs-creating-catalog-sources-that-automatically-pull-latest-images-from-entitled-registry).

**Comment by sgumpana** [comment]
> Can you update the GitHub actions workflows to use the new shared actions. See the files in https://github.com/cloud-native-toolkit/template-terraform-gitops/tree/main/.github/workflows as a reference.

Updated with latest Github action workflows.

**Pull request merged**
